### ISSUE TITLE
Prevent reuse of local variables for better debugging experience

### ISSUE THREAD

**Issue by csmuller** [neow3j/neow3j#269]
There are cases in which the JVM byte code reuses local variables such that the value stored at that variables index can represent something else than the type seen in the source code. Consider the example below. The variable `value` is first used as a byte array as expected. But, if the exception gets thrown that variable slot is reused for the exception. In the neo debugger the variable therefore shows the value of the exception as soon as we step into the catch block. That is obviously not desirable.

```
    public static int main(byte[] b) throws Exception {
        int n = 0;
        try {
            byte[] value = Storage.get(b);
            if (value == null) {
                throw new Exception("Value not found.");
            }
            n = 1;
        } catch (Exception e) {
            n = 2;
        }
        return n;
    }
```

**Comment by gsmachado** [comment]
I've seen that we merged a PR in the context of this issue (#435).
So, #435 was just to prevent this issue from frequently happening and not the solution, right?

Should we prioritize this somehow, or is this not a recurring problem? What do you think?

**Comment by csmuller** [comment]
Hmm, this must have been a mistake. It's issue #311 that is related to #435. This issue still remains open. But it is a minor bug in my opinion.

**Comment by gsmachado** [comment]
@mialbu hmm... what about this one?

Should we plan to fix this soon?

FYI @csmuller

**Comment by csmuller** [comment]
> Should we plan to fix this soon?

No, currently, this has less priority.
